### ISSUE TITLE
Is the title too specific?

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#11]
A slightly more general version is:

"The Joker: A custom Monte Carlo sampler for periodic radial velocity data"

but that is boring as hell and doesn't catch the eye as well as explicitly mentioning binary stars and exoplanets. I don't have a strong opinion, but want to raise the point for discussion.

**Comment by davidwhogg** [comment]
No strong opinion. I just want exoplanet RV people and binary star people to notice it.

**Comment by davidwhogg** [comment]
I am coming around to liking this title. Let's only re-open this issue if Rix asks for a title change (we should prompt him).
