### ISSUE TITLE
Remove pinned numpy and pytables constraints

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#118]
See:
- https://github.com/numpy/numpy/issues/21079
- https://github.com/PyTables/PyTables/issues/933

**Comment by adrn** [comment]
Also need to re-enable windows wheel builds.

**Comment by adrn** [comment]
Oof. Closing because I couldn't get pytables to build on windows on actions anyways...

**Comment by redeaglekr** [comment]
Hi,

 I am still getting the error

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

 with numpy == 1.20.3, when using thejoker. 

 I tried uninstalling numpy 1.20.3 and installing the latest version of numpy (1.22.3), but no solution.

Any fixes yet?

**Comment by adrn** [comment]
@redeaglekr That is usually a local installation issue -- could you try re-installing thejoker? Try: `pip uninstall thejoker` and then `pip install thejoker`?

**Comment by redeaglekr** [comment]
Solved!! Thanks.
