### ISSUE TITLE
Update to use pymc instead of pymc3

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#122]
Release a new major version that switches to pymc instead. 

But this needs to wait until the relevant functionality in `exoplanet` is also pymc-compatible (cc @dfm).

**Comment by dfm** [comment]
ref: https://github.com/exoplanet-dev/exoplanet/issues/234

I've been up to my eyeballs, but it truly shouldn't be too hard to make these updates since `exoplanet-core` is already compatible!

**Comment by dfm** [comment]
Tracking updates here: https://github.com/exoplanet-dev/exoplanet/pull/271

**Comment by adrn** [comment]
Handled in #127 !
