### ISSUE TITLE
Arviz error due to SciPy dependency

### ISSUE THREAD

**Issue by stephtdouglas** [adrn/thejoker#136]
Arviz has a bugged import statement that raises an error when using it with the joker - [issue here](https://github.com/arviz-devs/arviz/issues/2336). This is due to changes in scipy >=1.13. I was able to solve it by downgrading to scipy 1.10 (as seen in my solution for #135 ); until the next Arviz update, you may need to specify an older scipy version.

**Comment by adrn** [comment]
Thanks for reporting this! It looks like there's an arviz release from July, so I think this is resolved? (I haven't seen any errors related to this with the latest versions)
