### ISSUE TITLE
New experiment structure:

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#18]
- [x] Experiment 1: generate fake data with e=0.643, P=100.09 day, asini = 0.42 R_sun (or some reasonable set of parameters with high eccentricity) - 4 observation times uniformly sampled in a ~3 year window
- [x] Experiment 2: (what is currently Experiment 1) Run on a Troup star with few observations
- [x] Experiment 3: (what is currently Experiment 2) Run on a Troup star with many observations, downsample successively. Highlight switchover to `emcee`
- [x] Experiment 4: Run with full set of observations from Experiment 3 with uncertainties * [2,4,8,16]
- [ ] Experiment 5: motivated by the fact that some data points seem to carry a lot of information (demonstrated in Exp 3), repeat analysis from Experiment 1, but move the observation time of data point 4 through 1 cycle in period (in 8 steps). At certain phases, this point is very informative - we can use our tools to develop scheduling priorities.

**Comment by davidwhogg** [comment]
When we do experiment 5, we want to be working with a data set that is big enough that the posterior is very informative, but small enough that it is clearly and badly multi-modal

**Comment by adrn** [comment]
@davidwhogg agreed - it's been a challenge finding the right random number seed :)
