### ISSUE TITLE
should we put light conditional priors on the linear amplitudes?

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#2]

**Comment by davidwhogg** [comment]
Right now the text punts this point, saying that the implicit priors on the linear amplitudes are very broad. I think we should leave it this way for now. One reason:

It is absurd to have priors on the amplitudes that do not depend on the non-linear parameters. Think about it! So I think we *have* to make the amplitude priors arbitrarily broad.

All that said, my applied math friends say you should always add something on the diagonal before you run the `solve()` operator. It helps when the data get uninformative.

**Comment by davidwhogg** [comment]
I am now leaning strongly to NO to the question asked.

If we put priors on, we have to discuss, and discuss why we can't make them depend on the nonlinears.

**Comment by adrn** [comment]
We have support for this now, working on documentation of that feature now.
