### ISSUE TITLE
define Nsample and workflow around resampling with emcee

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#3]

**Comment by davidwhogg** [comment]
The emcee workflow should be:

- If all samples are within a neighborhood of size Q P^2 / (2 pi T) then switch to emcee.
- If emcee delivers a sampling with any evidence of a substantially larger neighborhood, go back to the importance sampling.

**Comment by davidwhogg** [comment]
I wrote the text for this, so I think this goes off to an implementation issue...
