### ISSUE TITLE
Convince DFM that this is useful

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#32]
OK, not exactly, but we need to add more words to the intro and discussion to explain why this is more desirable than using DNest. We want to explicitly state that you don't have to do any 2nd order tests of your samples to try to assess whether you are converged / have a true sampling from the posterior pdf. Starting with a dense enough (define) prior sampling, if *The Joker* returns many samples, you "just know" that you are done.

**Comment by davidwhogg** [comment]
I put in a bit more just now. Can we get @dfm to audit, adjust, and close this?
