### ISSUE TITLE
Make latex_labels an attribute of OrbitalParams with correct units

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#40]
The latex labels for the parameter names should automatically add the units, not hard-set like they are now.
```python
latex_labels = [r'$\ln (P/{\rm day})$', '$e$', r'$\omega$ [deg]', r'$\phi_0$ [deg]',
                's [m s$^{-1}]$', r'$K$ [m s$^{-1}$]', '$v_0$ [km s$^{-1}$]']
```

**Comment by davidwhogg** [comment]
shouldn't it be `\ln (P/[1\,{\rm d}])` or something like that?

**Comment by adrn** [comment]
'd' alone is too ambiguous to me so I prefer to just write out day

**Comment by davidwhogg** [comment]
I was more talking about the 1 than the abbreviation

**Comment by adrn** [comment]
¯\_(ツ)_/¯
