### ISSUE TITLE
Experiment 1 needs an informative example too

### ISSUE THREAD

**Issue by davidwhogg** [adrn/thejoker#43]
Can we do a good case that is effectively unimodal as well?

**Comment by adrn** [comment]
You don't think that's redundant with top of Experiment 3 / Figure 8?

**Comment by davidwhogg** [comment]
No -- because that is making a different point. I just don't think our FIRST example should give such a crazy posterior. It doesn't inspire confidence!

**Comment by adrn** [comment]
I think it *does* inspire confidence -- isn't the point to be able to sample from a crazy posterior?? Will see what Rix thinks

**Comment by adrn** [comment]
I'm punting on this -- let's see what the referee says and discuss before resubmission.

**Comment by davidwhogg** [comment]
Fine with me!
