### ISSUE TITLE
prove to Hogg that equation (1) is correct

### ISSUE THREAD

**Issue by davidwhogg** [adrn/thejoker#5]
- [ ] give him a paper-and-pen proof, by sms, and
- [ ] equation (1) makes no reference to P or phi_0, so give a second equation that gives f in terms of these.

**Comment by adrn** [comment]
The original version of Eq. 1 was copied from the code you wrote! I was just making sure I believed it. But actually there is a simpler way to write it in terms of Eq. 65 [in this paper](http://arxiv.org/pdf/1009.1738v2.pdf). I updated the text to use our parametrization. 

BTW: Winn 2010 is not the relevant reference -- it is [Murray & Correia](http://arxiv.org/abs/1009.1738) from the same book. Winn 2010 refers to that work.

**Comment by davidwhogg** [comment]
I believe you, but shouldn't
