### ISSUE TITLE
Finish referee report

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#57]
> The goal is to use this to "measure the undetectable" (a recurring theme in
> some of the authors' work) - to use hierarchical inference to make statements
> about the population when each object in that population has it properties
> only poorly constrained. Regarding the above point about measuring the
> undetectable, it might be worth referring to one or two papers outside of
> exoplanets where that kind of thing has been done.

Can you audit any redish text in the updated manuscript?

**Comment by adrn** [comment]
Yo @davidwhogg -- can we get this done today?

**Comment by davidwhogg** [comment]
What about mandel? Am I too late?

**Comment by adrn** [comment]
@davidwhogg you have 24h52m40s
