### ISSUE TITLE
Mention SMBHB's 

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#6]
This project is also relevant for supermassive black hole binary searches and population inference:

https://ui.adsabs.harvard.edu/#abs/2016arXiv160401020C/abstract
https://ui.adsabs.harvard.edu/#abs/2015MNRAS.453.1562G/abstract

**Comment by davidwhogg** [comment]
And also cite LIGO searches -- Farr mentioned this to me in blog comments.
