### ISSUE TITLE
Add example for assumed circular orbit

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#60]
Just need to sample prior assuming circular (sample over P, phi0)

**Comment by adrn** [comment]
Alternatively, add a flag to `TheJoker` to assume circularity.

cc @caprastro

**Comment by adrn** [comment]
This is added in #80 - hopefully the new examples will appear on readthedocs once I resolve some build issues over there...

**Comment by adrn** [comment]
Example now live: https://thejoker.readthedocs.io/en/latest/examples/custom-prior-sampling.html

**Comment by caprastro** [comment]
exciting!
