### ISSUE TITLE
Add option to produce >1 samples in K, v0 for a given set of nonlinear parameters

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#62]
Since we post-process to produce samples in the linear parameters, we could produce more than 1...

**Comment by davidwhogg** [comment]
...with relevant documentation warnings that this will introduce sample covariances (such that N_eff will not equal N_sample).

**Comment by adrn** [comment]
This is easy to do, but do we want to?

**Comment by adrn** [comment]
Make this a parameter, throw a warning about N_effective

**Comment by adrn** [comment]
Done in #91
