### ISSUE TITLE
Scripts need to be updated

### ISSUE THREAD

**Issue by stephtdouglas** [adrn/thejoker#68]
I can run at least the basic RVData/Sampler example, but the scripts in the scripts/ directory are out of date and call modules that don't exist anymore.

**Comment by adrn** [comment]
Looking at the scripts, yea, they are super old and way out of date! What would you like to see in there?

**Comment by stephtdouglas** [comment]
I think the main things are updated syntax, and a simple example that goes all the way through the rejection sampling and MCMC stages without using multiprocessing. The examples in the docs already include a good walkthrough of the rejection sampling step, the main thing for me now is moving to emcee.  I know the multiprocessing is important for speed and it's helpful to have those examples too, but in terms of understanding what's happening it'd be nice to have a single processor example. Some of the things I feel I'm missing are how variables need to change to move over to using emcee, and what to do if the rejection sampler yields a multi-modal posterior that doesn't accept more samples even if I cut down the sample space.

**Comment by adrn** [comment]
I decided to remove the scripts and will instead point people to a working "pipeline" code that uses The Joker, e.g., https://github.com/adrn/hq
