### ISSUE TITLE
feature request: inferring RV offsets

### ISSUE THREAD

**Issue by benjaminpope** [adrn/thejoker#79]
Hi Adrian,

Just re chat with @davidwhogg - it would be good to be able to add a linear parameter for the zero point offsets for merging data from different telescopes. This is both useful to projects we're currently doing and IMO to doing quicklook merging of heterogeneous sparsish RV surveys.

Cheers,

Ben

**Comment by adrn** [comment]
This is a good idea - I'll have a think about what the API would look like.

**Comment by benjaminpope** [comment]
My guess is that the most natural way to do this from a UX point of view would be to pass the sampler [dataset1, dataset2..., datasetN] where each is an RVData object.

**Comment by adrn** [comment]
Done in #91!
