### ISSUE TITLE
Import error with newest version, and unit error with downgraded version

### ISSUE THREAD

**Issue by leerosenthalj** [adrn/thejoker#80]
With the latest versions of twobody and thejoker installed, I see the following error when attempting to import thejoker.sampler.JokerParams:

`ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216` .

When I install the downgraded versions of twobody and thejoker, I see the following astropy error when attempting to run rejection sampling:

`UnitConversionError: 'rad' (angle) and 'd rad' are not convertible` .

This is with (I believe) appropriate units; u.day on Pmin and Pmax in prior, u.day on the barycentric times, and u.m/u.s on velocities and velocity errors.

Do either of these look familiar?

**Comment by adrn** [comment]
My guess would be `thejoker` is finding a previously installed version of `twobody`. Could you try:

```python
import twobody
print(twobody.__file__)
```
and post the output or email to me?

I've run in to similar things, and have had to do something like: 
```
rm -rf /path/to/python/lib/site-packages/twobody*
pip install git+https://github.com/adrn/twobody
```

**Comment by adrn** [comment]
Also: sorry the installation didn't go more smoothly!

**Comment by leerosenthalj** [comment]
No problem, thanks so much for responding! Here is the output:

/Users/lee/anaconda/lib/python3.6/site-packages/twobody/__init__.py

Should I wipe it and pip install as you've described above?

**Comment by adrn** [comment]
You could try that, yes, but depending on your needs / timescale, you might wait a few days: I'm planning to do new releases of twobody and thejoker by the end of the week. If you need to deal with this now, you can try (but beware of the `rm -rf`!):

```
rm -rf /Users/lee/anaconda/lib/python3.6/site-packages/twobody*
rm -rf /Users/lee/anaconda/lib/python3.6/site-packages/thejoker*
pip install git+https://github.com/adrn/twobody
pip install git+https://github.com/adrn/thejoker
```

(this has worked for others).

**Comment by leerosenthalj** [comment]
That's good to know; I'm happy to wait, since my goals aren't
time-sensitive. Thanks again for your help!

**Comment by adrn** [comment]
OK cool! I'll let you know when the new versions are ready to install

**Comment by adrn** [comment]
Hi @leerosenthalj - I've just released new versions of both `twobody` and `thejoker`. I would recommend deleting the previous ones you tried to install to avoid any issues:

```
rm -rf /Users/lee/anaconda/lib/python3.6/site-packages/twobody*
rm -rf /Users/lee/anaconda/lib/python3.6/site-packages/thejoker*
pip install thejoker
```

This might produce an error about `numpy`, but on my machine it still installed properly so I'm not sure what caused the error...

**Comment by adrn** [comment]
And please let me know if you run into any issues!

**Comment by leerosenthalj** [comment]
Thanks! Twobody is now installing without a hitch, but the attempt to
pip-install thejoker returns the error copied below. Doesn't seem to be
related to numpy. Also, the referenced directory doesn't seem to exist past
pip-install-ccd-etc.

Again, no rush to solve this. I'm excited to use thejoker for some
hierarchical analysis, but it's not time-sensitive work.

cythoning thejoker/sampler/fast_likelihood.pyx to
thejoker/sampler/fast_likelihood.c


error:
/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-install-ccd1ix2c/thejoker/thejoker/sampler/fast_likelihood.pyx

**Comment by adrn** [comment]
Hmm, interesting. Do you have cython installed? Could you send me the full output, or is that it? thanks!

**Comment by leerosenthalj** [comment]
Requirement already satisfied: cython in
/Users/lee/anaconda/lib/python3.6/site-packages (0.29.5)

lee:T $ pip install thejoker

Collecting thejoker

  Using cached
https://files.pythonhosted.org/packages/9c/36/f957ab95be93c940bb10244cd8f5debf5b36e8a0c9229307ec1abfc91146/thejoker-0.2.tar.gz

Requirement already satisfied: astropy in
/Users/lee/anaconda/lib/python3.6/site-packages (from thejoker) (3.1.1)

Requirement already satisfied: twobody>=0.5 in
/Users/lee/anaconda/lib/python3.6/site-packages (from thejoker) (0.5)

Requirement already satisfied: scipy in
/Users/lee/anaconda/lib/python3.6/site-packages (from thejoker) (1.2.0)

Requirement already satisfied: h5py in
/Users/lee/anaconda/lib/python3.6/site-packages (from thejoker) (2.9.0)

Requirement already satisfied: schwimmbad in
/Users/lee/anaconda/lib/python3.6/site-packages (from thejoker) (0.3.0)

Requirement already satisfied: numpy>=1.13.0 in
/Users/lee/anaconda/lib/python3.6/site-packages (from astropy->thejoker)
(1.16.1)

Requirement already satisfied: six in
/Users/lee/anaconda/lib/python3.6/site-packages (from h5py->thejoker)
(1.12.0)

Building wheels for collected packages: thejoker

  Building wheel for thejoker (setup.py) ... error

  Complete output from command /Users/lee/anaconda/bin/python -u -c "import
setuptools,
tokenize;__file__='/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-install-shg4fedh/thejoker/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d
/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-wheel-ulfyym_i
--python-tag cp36:

  running bdist_wheel

  running build

  running build_py

  creating build

  creating build/lib.macosx-10.7-x86_64-3.6

  creating build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/conftest.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/plot.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/version.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/log.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/_astropy_init.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/cython_version.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/utils.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/stats.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/data.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

  creating build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

  copying thejoker/tests/test_plot.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

  copying thejoker/tests/__init__.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

  copying thejoker/tests/test_data.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

  copying thejoker/tests/setup_package.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

  creating build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/sampler/params.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/sampler/multiproc_helpers.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/sampler/io.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/sampler/__init__.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/sampler/mcmc.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/sampler/likelihood.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/sampler/sampler.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/sampler/samples.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/sampler/setup_package.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  creating build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/test_likelihood.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/__init__.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/test_io.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/test_fast_likelihood.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/test_params.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/test_mcmc.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/test_multiproc_helpers.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/test_samples.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/helpers.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/sampler/tests/test_sampler.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

  copying thejoker/_compiler.c -> build/lib.macosx-10.7-x86_64-3.6/thejoker

  copying thejoker/sampler/fast_likelihood.c ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

  copying thejoker/tests/coveragerc ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

  running build_ext

  building 'thejoker._compiler' extension

  creating build/temp.macosx-10.7-x86_64-3.6

  creating build/temp.macosx-10.7-x86_64-3.6/thejoker

  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g
-fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/lee/anaconda/include -arch
x86_64 -I/Users/lee/anaconda/include -arch x86_64
-I/Users/lee/anaconda/include/python3.6m -c thejoker/_compiler.c -o
build/temp.macosx-10.7-x86_64-3.6/thejoker/_compiler.o

  gcc -bundle -undefined dynamic_lookup -L/Users/lee/anaconda/lib -arch
x86_64 -L/Users/lee/anaconda/lib -arch x86_64 -arch x86_64
build/temp.macosx-10.7-x86_64-3.6/thejoker/_compiler.o -o
build/lib.macosx-10.7-x86_64-3.6/thejoker/_compiler.cpython-36m-darwin.so

  cythoning thejoker/sampler/fast_likelihood.pyx to
thejoker/sampler/fast_likelihood.c

  error:
/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-install-shg4fedh/thejoker/thejoker/sampler/fast_likelihood.pyx



  ----------------------------------------

  Failed building wheel for thejoker

  Running setup.py clean for thejoker

Failed to build thejoker

Installing collected packages: thejoker

  Running setup.py install for thejoker ... error

    Complete output from command /Users/lee/anaconda/bin/python -u -c
"import setuptools,
tokenize;__file__='/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-install-shg4fedh/thejoker/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-record-didxpou0/install-record.txt
--single-version-externally-managed --compile:

    running install

    running build

    running build_py

    creating build

    creating build/lib.macosx-10.7-x86_64-3.6

    creating build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/conftest.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/plot.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/version.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/log.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/_astropy_init.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/__init__.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/cython_version.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/utils.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/stats.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/data.py -> build/lib.macosx-10.7-x86_64-3.6/thejoker

    creating build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

    copying thejoker/tests/test_plot.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

    copying thejoker/tests/__init__.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

    copying thejoker/tests/test_data.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

    copying thejoker/tests/setup_package.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

    creating build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/sampler/params.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/sampler/multiproc_helpers.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/sampler/io.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/sampler/__init__.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/sampler/mcmc.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/sampler/likelihood.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/sampler/sampler.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/sampler/samples.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/sampler/setup_package.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    creating build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/test_likelihood.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/__init__.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/test_io.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/test_fast_likelihood.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/test_params.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/test_mcmc.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/test_multiproc_helpers.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/test_samples.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/helpers.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/sampler/tests/test_sampler.py ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler/tests

    copying thejoker/_compiler.c ->
build/lib.macosx-10.7-x86_64-3.6/thejoker

    copying thejoker/sampler/fast_likelihood.c ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/sampler

    copying thejoker/tests/coveragerc ->
build/lib.macosx-10.7-x86_64-3.6/thejoker/tests

    running build_ext

    building 'thejoker._compiler' extension

    creating build/temp.macosx-10.7-x86_64-3.6

    creating build/temp.macosx-10.7-x86_64-3.6/thejoker

    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g
-fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/lee/anaconda/include -arch
x86_64 -I/Users/lee/anaconda/include -arch x86_64
-I/Users/lee/anaconda/include/python3.6m -c thejoker/_compiler.c -o
build/temp.macosx-10.7-x86_64-3.6/thejoker/_compiler.o

    gcc -bundle -undefined dynamic_lookup -L/Users/lee/anaconda/lib -arch
x86_64 -L/Users/lee/anaconda/lib -arch x86_64 -arch x86_64
build/temp.macosx-10.7-x86_64-3.6/thejoker/_compiler.o -o
build/lib.macosx-10.7-x86_64-3.6/thejoker/_compiler.cpython-36m-darwin.so

    cythoning thejoker/sampler/fast_likelihood.pyx to
thejoker/sampler/fast_likelihood.c

    error:
/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-install-shg4fedh/thejoker/thejoker/sampler/fast_likelihood.pyx



    ----------------------------------------

Command "/Users/lee/anaconda/bin/python -u -c "import setuptools,
tokenize;__file__='/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-install-shg4fedh/thejoker/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-record-didxpou0/install-record.txt
--single-version-externally-managed --compile" failed with error code 1 in
/private/var/folders/m2/d_mgqb5m8xjgys00r6bm8b780000gp/T/pip-install-shg4fedh/thejoker/

**Comment by adrn** [comment]
Oops, yea, looks like I screwed up the packaging. Try again now? I just pushed a bugfix release that I hope fixes this issue.

**Comment by leerosenthalj** [comment]
Hi Adrian,

Successfully imported! Thanks so much for your patience and help, I look
forward to using (and citing) this code. I actually was at the Flatiron
this week for a hack week, and sat down with David Hogg to talk about some
potential applications to long-baseline RV trends. I'll let you know if I
have any other questions.

Best,
Lee
