### ISSUE TITLE
rejects lots of samples if you infer jitter

### ISSUE THREAD

**Issue by benjaminpope** [adrn/thejoker#85]
Hi Adrian,

On a particular HIRES dataset (which I can send you) which is a jittery M dwarf I try three samplers:

params_trend = JokerParams(P_min=0.5*u.day, P_max=10.*u.day,jitter=(np.log(5.**2), 0.5), jitter_unit=u.m/u.s)
params_trend = JokerParams(P_min=0.5*u.day, P_max=10.*u.day,jitter=(np.log(5.**2), 0.01), jitter_unit=u.m/u.s)
params_trend = JokerParams(P_min=0.5*u.day, P_max=10.*u.day,jitter=5*u.m/u.s)

with 

samples_trend = joker.rejection_sample(data, n_prior_samples=2**20)

The first samples *very* badly, getting one (one!) good sample. The middle one, where we have a ridiculously tight prior on 5 m/s, gets a pretty good return on investment of 12616 good samples, and setting jitter explicitly gets a healthy 21767. 

It doesn't seem reasonable to me that even a fairly moderate prior widtih rejects so overwhelmingly large a number of solutions... am I wrong or is there something amiss with the normalization of the jitter term or something?

All the best,

Ben

**Comment by adrn** [comment]
I'll take a look! Would you mind sending me the data? I will delete after this experiment in case there are data sharing issues :)

**Comment by adrn** [comment]
Hm, I do see the same thing, but I don't have a great answer for you! My guess would be that the data don't have a clear Keplerian signal, so the jitter prior tries to pull the jitter value to 0, but then it doesn't find a good orbital solution for the data, so few samples get returned? When the jitter prior is tight around 5 m/s, it allows more flexibility with the fits, so many more samples are returned. Here are the jitter values returned from your cases 1 (blue) and 2 (orange) - see in case 1 the jitter values for the returned samples are small:

![image](https://user-images.githubusercontent.com/583379/53601247-a792ad00-3b79-11e9-9bbd-49af3d128645.png)

**Comment by benjaminpope** [comment]
Weird - even setting a very wide prior I don't get anything very good.

50% of cadences are followed by one a day later, and 25% by another one a
day after that - so I imagine we are at ~ mean Nyquist for ~ 2 days, though
the shortest separations would give much shorter periods. I wonder if we
have any sampling problems due to aliasing (164 epochs over 16 years is
pretty irregular!).

On Thu, Feb 28, 2019 at 5:06 PM Adrian Price-Whelan <
notifications@github.com> wrote:

> Hm, I do see the same thing, but I don't have a great answer for you! My
> guess would be that the data don't have a clear Keplerian signal, so the
> jitter prior tries to pull the jitter value to 0, but then it doesn't find
> a good orbital solution for the data, so few samples get returned? When the
> jitter prior is tight around 5 m/s, it allows more flexibility with the
> fits, so many more samples are returned. Here are the jitter values
> returned from your cases 1 (blue) and 2 (orange) - see in case 1 the jitter
> values for the returned samples are small:
>
> [image: image]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_583379_53601247-2Da792ad00-2D3b79-2D11e9-2D9bbd-2D49af3d128645.png&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=aUviAUQi7pS114vc1yag2TqvdKYbSc46sVyEMVe4XXQ&s=9bw4Szee499PFjYzUTimzHWiRB0MkEGPckLz6cObMwQ&e=>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_adrn_thejoker_issues_85-23issuecomment-2D468457695&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=aUviAUQi7pS114vc1yag2TqvdKYbSc46sVyEMVe4XXQ&s=f0mUZbvy1FpK_IFnuaj6PQkQbeDRJ84yf_hqFmGYbKA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFvsFQa9UtimgMk4qtYRayWnQAl65pgIks5vSFLWgaJpZM4bXrv4&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=aUviAUQi7pS114vc1yag2TqvdKYbSc46sVyEMVe4XXQ&s=XCSWcNiH00Yh-MlAPiW-ZQPD1eDSWRCTcTgQjl5ZmTY&e=>
> .
>
-- 
Dr Benjamin Pope
NASA Sagan Fellow
Center for Cosmology and Particle Physics
New York University
726 Broadway
New York, NY 10003

**Comment by adrn** [comment]
I take from this that you expect there to be a signal in there?

**Comment by benjaminpope** [comment]
Not necessarily - but we want to robustly infer the stellar jitter and put
upper limits on K for any short period planets. We expect a non detection
but a rigorous one.
On Thu, 28 Feb 2019 at 6:02 pm, Adrian Price-Whelan <
notifications@github.com> wrote:

> I take from this that you expect there to be a signal in there?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_adrn_thejoker_issues_85-23issuecomment-2D468474506&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=fW4d2lEXl8ES4a0nonU8Pz4qZWpOJlfM7rhwWdq3sYs&s=GbkAKsnJ3iKyfVDqfn0KSxSxQ4sazGsK1o258hRj410&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFvsFfY2zxEOkzkL8yl9VqfFuZQvL-5F3-2Dks5vSGAcgaJpZM4bXrv4&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=fW4d2lEXl8ES4a0nonU8Pz4qZWpOJlfM7rhwWdq3sYs&s=EUVhuqyqguEF2OxjaP0TWK3cL2-zDSySNpK4HgNnzFM&e=>
> .
>
-- 
Dr Benjamin Pope
NASA Sagan Fellow
Center for Cosmology and Particle Physics
New York University
726 Broadway
New York, NY 10003

**Comment by adrn** [comment]
Got it! OK then I think the only thing you can do is (a) go to many more samples, and (b) try a few different jitter priors. I'll put together a little demo notebook for what I would recommend trying and send it your way!

**Comment by benjaminpope** [comment]
Thanks!

On Fri, Mar 1, 2019 at 8:18 AM Adrian Price-Whelan <notifications@github.com>
wrote:

> Got it! OK then I think the only thing you can do is (a) go to many more
> samples, and (b) try a few different jitter priors. I'll put together a
> little demo notebook for what I would recommend trying and send it your way!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_adrn_thejoker_issues_85-23issuecomment-2D468661710&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=oWiXVh9rNol51JV_R0MNlwUpCx-7jERnA6q9cNq2rMY&s=Mlc3pyjcOYcFlCv6itmcSiRDmCIWNRteb62E_KvoXFM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFvsFUPu-2D1D-5FTPHO-5FheN76dY0w0LX63Xks5vSSiHgaJpZM4bXrv4&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=oWiXVh9rNol51JV_R0MNlwUpCx-7jERnA6q9cNq2rMY&s=YUiT_Kx2E0-ztT37g-tpTQOXOxdvELBqAKslLcXyPcc&e=>
> .
>
-- 
Dr Benjamin Pope
NASA Sagan Fellow
Center for Cosmology and Particle Physics
New York University
726 Broadway
New York, NY 10003
