### ISSUE TITLE
Does the meaning of K depend on e?

### ISSUE THREAD

**Issue by davidwhogg** [adrn/thejoker#86]
Here's my question: If you FIX total system mass and FIX period and FIX inclination, but consider orbits of different eccentricity, will they have the same value of the velocity semi-amplitude K? Do you know what I'm sayin'?

**Comment by dfm** [comment]
No. See eq. ~13 of: http://exoplanets.astro.yale.edu/workshop/EPRV/Bibliography_files/Radial_Velocity.pdf

K scales as 1/sqrt(1-e^2)

**Comment by davidwhogg** [comment]
Oh yay! I think you have answered our question. I think I can make a new issue that makes more sense, which is "make the meaning of K NOT depend on e, internally within The Joker".

**Comment by davidwhogg** [comment]
ps, Debra Fischer consistently produces useful stuff for the exoplanet community. We're not worthy.

**Comment by adrn** [comment]
Thanks for the pointer @dfm
