### ISSUE TITLE
Connect with exoplanet

### ISSUE THREAD

**Issue by adrn** [adrn/thejoker#89]
It would be nice to make it easy for users to take samples from The Joker and initialize a new sampling with `exoplanet` for unimodal solutions. Putting this on the wish list for the overhaul I'm working on...but will need some help from @dfm !

**Comment by dfm** [comment]
It should be pretty plug and play if you're willing to take up the extra dependency! I have a few ideas for better parameterizations that this tutorial, but it wouldn't be far different: http://exoplanet.dfm.io/en/stable/tutorials/rv/

**Comment by adrn** [comment]
Done in #91
