### ISSUE TITLE
Error when writing to h5py file

### ISSUE THREAD

**Issue by stephtdouglas** [adrn/thejoker#99]
When trying to write out samples to an h5py group, I get the following error: "Error: local variable 'ext' referenced before assignment"

I'm calling it as 
`samples.write(group,overwrite=True)`

I think this line is the culprit: 
https://github.com/adrn/thejoker/blob/4d42d1639bda377d9d5e5d295c7daed613fe7fb9/thejoker/samples.py#L395
Since I'm not passing in a string, the preceding if statement doesn't execute and "ext" is not defined.

**Comment by adrn** [comment]
Oops! Yep, totally a bug. I think I just fixed it on master - could you try updating? Sorry, things are crazy right now so I've been a bit sloppier 😬

**Comment by stephtdouglas** [comment]
Yep, it runs now! 

No worries, I'm happy to beta test :)
